Actually obey `-fdefault-colseq`
OCamlPro/gnucobol pull request #101
Opened 2023-06-21 12:07 UTC by nberth

… which currently seems ignored for alphanumeric comparisons others than in `SORT`.

2023-06-21 15:57 UTC, nberth commented
Here's a bit of context on this.

While investigating a weirdly functioning `SEARCH ALL`, I actually observed that the resulting search algorithm did not operate according to any user-given collating sequences if (and only if) that sequence was specified using `-fdefault-colseq`. Other means of specifying the collating sequence (e.g, via the `ENVIRONMENT DIVISION`) seemed to make the search work properly.

Investigating further, it seems constant-folding does not operate according to the proper collating sequence. And it may also be the case that fast-comparisons (`-ffast-compare`) are also impacted.

A seemingly "easy" way to mitigate the last points would be to check on the status of (`current_`)`prog->collating_sequence` when performing constant folding and/or optimizing comparisons.

2023-06-21 17:45 UTC, GitMensch commented
Ideally both points would do the check via libcob functions and passing the collation.

2023-06-22 09:35 UTC, nberth commented
> Ideally both points would do the check via libcob functions and passing the collation.

Yes that would be ideal indeed. However, I don't think I'll have the time to implement that new approach right now (but I'd happily give it a try). May I suggest pushing the current PR upstream first, as this is primarily a bugfix?

(In the meantime, I've also added a test for `SEARCH ALL`.)

2023-06-22 12:25 UTC, GitMensch requested changes
the general idea and the test cases are fine; I'm also OK with "relay to libcob" - but it seems that both the wrong fields are adjusted (don't change current_program directly but its source fields) and checked alphanumeric (collating sequence for national literals)

please rework this (and _possibly_ keep [NOT] EQUALS also if a collation is specified)

2023-06-22 12:25 UTC, GitMensch commented on cobc/ChangeLog
> +	* parser.c (setup_program): properly record default collating sequence
you've adjusted parser.y ;-)

2023-06-22 12:25 UTC, GitMensch commented on cobc/parser.y
> +	switch (cb_default_colseq) {
something is wrong here, as this is later adjusted in `object_computer_sequence`;
from a quick glance you want to adjust the default of `alphanumeric_collation` and `national_collation`

2023-06-22 12:25 UTC, GitMensch commented on cobc/tree.c
> +		 && current_program->collating_sequence == NULL
it seems that the check for = and ~ below can still be done - and in the other cases the literal's class should likely be checked against national in which case `collating_sequence_n` must be compared

2023-06-22 15:33 UTC, GitMensch commented on cobc/parser.y
> +	switch (cb_default_colseq) {
I'd suggest to init both `alphanumeric_collation` and `national_collation` in `program_init_without_program_id` and `setup_program`, then later use it directly.

2023-06-22 15:34 UTC, GitMensch commented on cobc/tree.c
> +		 && current_program->collating_sequence == NULL
The new version of this code is fine!

2023-06-23 08:28 UTC, GitMensch approved these changes
LGTM, _consider_ the minor change to parser and feel free to commit.

2023-06-23 08:28 UTC, GitMensch commented on cobc/parser.y
> +		alphanumeric_collation = national_collation =
Setting the national collation to the alphanumeric collation is likely wrong- but that was the case in some of the removed code paths too.
You may always set it to `NULL` for now and leave a TODO marker, or leave as is (hm a TODO/CHECKME marker would be good in any case)

2023-06-23 10:02 UTC, closed without merging