Support for JOR files
OCamlPro/gnucobol pull request #141
Opened 2024-03-20 10:00 UTC by lefessan

JOR files are journals of COBOL executions. This commit implements
minimalist support for JOR files with the following features:
* extensible: the format can be easily extended in the future
* compact: the format is binary and does not take too much space on disk

Currently, the JOR file contains the arguments, the execution start
and stop times and per-file statistics of opens, reads, writes, starts
and closes operations.

2024-03-20 10:40 UTC, GitMensch requested changes
obviously this has one commit too much in currently; for the first draft see some notes in the review; the biggest question is (likely answered in NEWS and gnucobol.texi): why should a user want that, what is its practical purpose?

Should there be binaries under /bin that take an existing jor file and convert it to xml/json/text?

2024-03-20 10:40 UTC, GitMensch commented on libcob/common.h
> +};
put that above, add a trailing "_MAX" entry and use that max entry as index instead of `COB_JOR_FILE_OPERATIONS `

2024-03-20 10:40 UTC, GitMensch commented on libcob/jor.c
> +   Written by Emilien Lemaire and Fabrice Le Fessant.
So you did start that last year already, together with Emilien?

2024-03-20 10:40 UTC, GitMensch commented on libcob/jor.c
> +#include <sys/time.h>
as clangd and some compilers will tell you - these are not all used in the source, please cleanup

2024-03-20 10:40 UTC, GitMensch commented on libcob/jor.c
> +static int field_args ;
likely `unsigned int`, if you don't need a negative marker (and if that is used, it is often useful to double-check if that's a  good implementation)

2024-03-20 10:40 UTC, GitMensch commented on libcob/jor.c
> +#define TYPE_STRING16  11
enum?

2024-03-20 10:40 UTC, GitMensch commented on libcob/jor.c
> +}
likely replace in the caller

2024-03-20 10:40 UTC, GitMensch commented on libcob/jor.c
> +	}
use the common abort and message functions here or drop that part

2024-03-20 10:40 UTC, GitMensch commented on libcob/jor.c
> +	    !getenv ("COB_JOR_ENABLED")) return ;
that will be already be handled in the settings pointer, so this part can be removed

2024-03-20 10:40 UTC, GitMensch commented on libcob/fileio.c
`cob_jor_file_operation` is called often, so I think we _may_ check `!cobsetptr->cob_jor_enable` in this file instead (saving the function call and its resulting stack/register changes on in and out), possibly wrap that in a macro so you keep the single lines here. But I've done no perf tracing on this...

2024-03-20 10:40 UTC, GitMensch commented on libcob/jor.c
> +	if (!!cobsetptr) return ;
that would be an error, I therefore would suggest to drop that

2024-03-20 10:40 UTC, GitMensch commented on libcob/jor.c
the outline at the start is well done; please add doxygen comments to each of the functions as well

2024-03-20 11:13 UTC, GitMensch commented
What do you think of moving the stats to be only/mostly set on `save_status` as per Ron's implementation https://github.com/OCamlPro/gnucobol4/commit/4a61f7cab2bb4a3e8f3a5971cb3cd67fc8290775 https://github.com/OCamlPro/gnucobol4/commit/24a3751e47fdec140be50e445a4fb80c3223385d? 

What about merging the fileio stats (only active for programs that are compiled with tracing) to GC 3.3 (that would also include https://github.com/OCamlPro/gnucobol4/commit/980d0b41829de8952157c8264ec61d497e504497)?

2024-03-20 14:55 UTC, lefessan commented
The idea behind this PR is to be able to get a minimal trace of the execution, in production mode. This is not possible with standard tracing options that are too expensive. You can imagine a batch failing during the night, people might want to understand what happened exactly during the run, and maybe to preceding steps, without running them again in trace mode. Also, you get information like the time spent, the IO stats, and probably more in the future.

There are maybe other solutions, but I think it's worth investigating this mode.

And yes, there needs to be some program that will translate these binary files into json or something like that...

By the way, I am not really targeting 3.3, ideally, it's something that could land in 4.0 once 3.3 has been released.

2024-03-20 16:22 UTC, GitMensch commented
> By the way, I am not really targeting 3.3, ideally, it's something that could land in 4.0 once 3.3 has been released.

Ah, then please edit the PR to have that based on master then.
Still, it would be useful to check the review comments, including the question to do it at the same place: save_status and in 4.x consider to provide the option to disable/enable the file recording by file (using the IO_ options, see referenced commits).

> This is not possible with standard tracing options that are too expensive.

We still can consider to use these as basis -> check for a new trace value "binary" and in this case do the tracing you currently do.

In any case I suggest to write a plan (which includes your binary format), then send that to the developer mailing list for additional input - _especially_ when you target trunk.

2026-08-28 09:30 UTC, lefessan commented
I am not planning to continue this PR, but instead, maybe try using Open Telemetry

2026-08-28 09:30 UTC, closed without merging