Disable Windows error popups under testing environments
OCamlPro/gnucobol pull request #172
Opened 2024-08-21 15:53 UTC by ddeclerck

This silences the Windows error popups under testing environments (turns them into actual errors on stderr).

This required the use of `_CrtSetReportMode`, as the use of `SetErrorMode` did not help.

2024-08-21 18:48 UTC, GitMensch requested changes
That sounds very good in general.

Don't check for CI to not enable but check for something else, maybe
`if (!IsDebuggerPresent || !getenv ("DEBUG_POPUPS_WANTED"))`

The idea seems good but I can't see in the CI run if there are any testresults (and there is no testsuite.log artifact, so it _seems_ something didn't worked out).-

And please add the changelog entry.

2024-08-22 12:11 UTC, ddeclerck commented
Should be good this time.

Just wondering about the condition: should we keep the popups only when there is a debugger present AND  DEBUG_POPUPS_WANTED is set, or when either there is a debugger present OR DEBUG_POPUPS_WANTED is set ?

2024-08-22 12:31 UTC, GitMensch commented
"or", so that's fine for commit upstream (libcob) and the CI definition(s) here

2024-08-22 12:31 UTC, GitMensch approved these changes

2024-08-22 14:10 UTC, ddeclerck commented
> "or", so that's fine for commit

Is it ? I think I have to replace `||` by `&&` in the condition (the test is backwards ; when it evaluates to true, the popups are disabled).

2024-08-22 14:22 UTC, GitMensch commented
I'm sure you'll do the right thing for the spec "either debugger is running or that environment variable is set" 💪 .

2024-08-22 14:47 UTC, ddeclerck commented
Merged on SVN @ 5315.

2024-08-22 15:48 UTC, GitMensch commented
after a rebase this leaves only the CI adjustment - which should go to https://github.com/OCamlPro/gnucobol/pull/172 - so closing this

2024-08-22 15:48 UTC, closed without merging