Compare Gcos4gnucobol 3.x with Gnucobol-3.x
OCamlPro/gnucobol pull request #39
Opened 2022-05-19 12:41 UTC by lefessan

2022-05-19 20:14 UTC, GitMensch requested changes
for common patches please leave the msg catalogues out, they pot file is commonly recreated directly before a release and the updates to the language ones comes from the translation project.

2022-05-19 20:14 UTC, GitMensch commented on cobc/field.c
> +
The original issue with the loop was fixed in the meantime, is there still a reason for this change? If yes: should definitely get a testsuite entry.

2022-05-19 20:14 UTC, GitMensch commented on cobc/ppparse.y
> +	if (cb_fold_copy == COB_FOLD_LOWER || cb_fold_copy == COB_FOLD_BOTH) {
if both is added it should uppercase first, then lowercase (and actually this is what the commit log, says :-).
...

Is the folding both a GCOS related issue? Please elaborate.

2022-05-19 20:14 UTC, GitMensch commented on cobc/warning.def
> +CB_ONWARNDEF (cb_missing_newline, "missing-newline",
This one (the separate warning flag) can directly go into 3.x. As copyright assignments are done, you could do it directly, too (I just need your SF user to provide write access).

2022-05-19 20:19 UTC, GitMensch commented
For 5cc12e16b0dbfe8117332eee790f3866f6bb6fe6 I _think_ we discussed it would be useful to run `make distcheck` to see if it still works and to ideally also provide the resulting tarball as artifact. Did we?

2022-05-20 09:04 UTC, nberth commented
@GitMensch This PR is mostly to help us track the current diff between the branch with our pending contributions and the `gnucobol-3.x` branch.
About the CI, I am about to setup a new PR that makes the necessary changes. As there are some issues still with some commits above (fold-copy, already fixed issue, etc), I am also thinking of (force) rebasing the branch `gcos4gnucobol-3.x` to have the initial CI setup and GCOS config files only.

2022-05-20 09:47 UTC, closed without merging