Add context to aliases in configuration
OCamlPro/gnucobol pull request #93
Opened 2023-03-07 17:05 UTC by emilienlemaire

While working on configurations with @nberth, we discoverd that rules like `reserved: ALIAS*=CONTEXTUAL-WORD` in configuration files, the context sensitivity of `CONTEXTUAL-WORD` was never reported to the aliases.
A small example with the following code:
```cobol
       IDENTIFICATION   DIVISION.
       PROGRAM-ID.      prog.
       DATA             DIVISION.
       WORKING-STORAGE  SECTION.
       01  BYTE-LENGTH  PIC 9.
       01  X            CONSTANT AS BYTE-LENGTH OF BYTE-LENGTH.
       PROCEDURE        DIVISION.
           MOVE X TO BYTE-LENGTH.
           DISPLAY BYTE-LENGTH NO ADVANCING
           END-DISPLAY.
           STOP RUN.
```
If we run the compiler with `reserved: XX*=BYTE-LENGTH` and replace all `BYTE-LENGTH` in the code with `XX` we get the following errors:
```sh
test.cob:5: error: syntax error, unexpected BYTE-LENGTH
test.cob:6: error: syntax error, unexpected BYTE-LENGTH
test.cob:6: error: constant item 'X' requires a VALUE clause
test.cob:8: error: syntax error, unexpected BYTE-LENGTH
test.cob:9: error: syntax error, unexpected BYTE-LENGTH, expecting (
```
when the file is expected to compile.
After the changes introduced in this PR we can compile with contextual aliases.

This PR also fixes a small error in `config/ibm.conf`

2023-03-07 17:20 UTC, GitMensch commented on config/ibm.words
> +reserved:	POINTER-32
nice that you've spot the typo, the change was so small that I've directly checked that in (if I remember right the target branch will be updated tomorrow)

2023-03-07 17:21 UTC, GitMensch commented on .gitignore
> +.cache
changes to this file are unrelated to any other PR and I think this overlaps with #76; please have a look there

2023-03-07 17:43 UTC, GitMensch requested changes
The change itself looks good to me, please adjust the commit to remove the unrelated files (for example undo the commit, then revert/stash those) and add a test case (you already have presented one which is fine) to the testsuite (would go into syn_misc.at after the "aliases" test) and add an entry in cobc/Changelog.

For an example see https://github.com/OCamlPro/gnucobol/pull/88/files

2023-03-08 07:52 UTC, nberth commented
> ```cobol
>        01  X            CONSTANT AS BYTE-LENGTH OF BYTE-LENGTH.
> ```

@GitMensch Most documentations seem to make `BYTE-LENGTH` sensitive in "constant entry", which I *guess* in principle spans from the level (`01` above) to the terminating `.`. In practice, restricting "constant entry" to start right after `CONSTANT` makes sense, however I'm wondering whether the second `BYTE-LENGTH` above is actually legitimate.

2023-03-08 08:31 UTC, GitMensch commented
It is valid because the only thing that may be used there is a data-name, and therefore the data-names must be inspected.
Note that GnuCOBOL has (with the default std) uses context-sensitivity quite often and "with reduced scope", which enables it to compile a lot of different dialects by limiting their "special" reserved words to be tokenized as reserved word where it actually may be used as this - otherwise it is recognized as user-defined word (mostly data-name or label-name)

2023-03-08 15:18 UTC, GitMensch commented
@nberth : feel free to commit "upstream"

2023-03-08 15:19 UTC, GitMensch approved these changes

2023-03-08 19:55 UTC, GitMensch commented
Now upstream - thanks again.

2023-03-08 19:55 UTC, closed without merging