Add option to relax bound checks for ODO items (FR #437)
OCamlPro/gnucobol pull request #99
Opened 2023-06-20 08:02 UTC by nberth

Only ODO items for now, which actually makes this PR quite short.
I'm not sure what is to be relaxed about reference modifications.
If that stays like this, `-fcheck-record-bound` may not be the clearest of names; maybe `-frelax-odo-bound-checks` would suit better.

2023-06-20 10:18 UTC, GitMensch requested changes
I've retested with MF and the ODO item (and the minimum item) are never checked there either, even if bounds are checked (which is the default) or all checks are enabled.

I therefore see that this _should_ be a dialect option.
Please adjust the PR according to the updated specs in the [upstream FR](https://sourceforge.net/p/gnucobol/feature-requests/437/).

2023-06-20 10:18 UTC, GitMensch commented on cobc/flag.def
> +	_("  -fcheck-record-bound  check ODO item access against field founder instead of dynamic size"))
that description would be a different check (and _may_ be the right one for GCOS, as it is [per docs] the one that is used on IBM) - you are welcome to implement that (see adjusted specs in the upstream FR)

2023-06-20 17:22 UTC, GitMensch approved these changes
there were some "beauty" issues which I've checked in quickly; you may want to review those, then: feel free to commit the branch's diff to svn

2023-06-20 17:22 UTC, GitMensch commented on cobc/typeck.c
> +									 cb_build_cast_int (sub),
please revert this whitespace change (enough to do during commit into svn)

2023-06-21 06:57 UTC, nberth commented
Ok thanks for all the hints and specs.
Now upstream

2023-06-21 06:57 UTC, closed without merging